apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gke-backup-poc.fullname" . }}-configmap
  namespace: {{ .Release.Namespace }}
data:
  {{ .Values.configmap.index.name }}: {{ .Values.configmap.index.data }}
