apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "gke-backup-poc.fullname" . }}-cronjob
  namespace: {{ .Release.Namespace }}
  labels:
    type: cronjob
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ include "gke-backup-poc.fullname" . }}-cronjob
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
