apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "gke-backup-poc.fullname" . }}-job
  namespace: {{ .Release.Namespace }}
spec:
  template:
    spec:
      containers:
      - name: {{ include "gke-backup-poc.fullname" . }}-job
        image: perl:5.34.0
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  backoffLimit: 4
