apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "gke-backup-poc.fullname" . }}-networkpolicy
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      type: cronjob
  policyTypes:
  - Egress
  egress:
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
