apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gke-backup-poc.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  username: YWRtaW4=
  password: MWYyZDFlMmU2N2Rm
  