apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ include "gke-backup-poc.fullname" . }}-storage
  namespace: {{ .Release.Namespace }}
volumeBindingMode: WaitForFirstConsumer
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
reclaimPolicy: Retain